services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: app
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
