# .github/workflows/publish-contract.yml
name: Publish API Contract to GitHub Packages

on:
  push:
    branches:
      - main # 每当 main 分支有更新时触发

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@tobenot' # 明确指定 scope

      - name: Install dependencies and build
        run: npm ci && npm run build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
